import os
import argparse
from pathlib import Path
import pandas as pd
import pyarrow.parquet as pq
import numpy as np
from tqdm.auto import tqdm
from dataclasses import dataclass, field

@dataclass
class WindowShard:
    shard_id: int
    estimated_sizes_gb: list[float] = field(default_factory=list)
    transition_files: list[Path] = field(default_factory=list)

    @property
    def estimated_size_gb(self) -> float:
        return np.sum(self.estimated_sizes_gb)



def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run Temporal Builder for ABR-Sim")
    parser.add_argument(
        "--input_dir",
        type=str,
        required=True,
        help="Directory containing the input Tabular Files generated by the ABR Simulator.",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="./temporal_results",
        help="Directory to save the output CSV files generated by Temporal Builder.",
    )
    parser.add_argument(
        "--max_shard_size",
        type=int,
        default=40,
        help="Maximum Estimated Size (in GB) for each output shard."
    )
    parser.add_argument(
        "--window_context_size",
        type=int,
        default=4,
        help="Number of transitions to include in the context of each temporal window."
    )
    parser.add_argument(
        "--window_target_size",
        type=int,
        default=1,
        help="Number of transitions to include in the target of each temporal window."
    )
    return parser.parse_args()

def estimate_file_size_gb(num_windows: int, window_size: int, avg_transition_size_kb: float = 4.0) -> float:
    """
    Estimate the file size in GB based on the number of transitions and average size per transition in KB.
    """

    window_size_kb = window_size * avg_transition_size_kb
    total_size_kb = num_windows * window_size_kb
    total_size_gb = total_size_kb / 1e+6

    return total_size_gb

def get_transition_count(file_path: Path) -> int:
    match file_path.suffix.lower():
        case ".csv":
            df = pd.read_csv(file_path, usecols=["scenario_id"])
            return len(df)
        
        case ".parquet":
            parquet_file = pq.ParquetFile(file_path)
            return int( parquet_file.metadata.num_rows)
        
        case _:
            raise ValueError(f"Unsupported file format for transition count: {file_path.suffix}")

def shard_transition_files(transition_directory: Path, temporal_window_size: int, max_shard_size_gb: float) -> list[WindowShard]:

    transition_files = sorted(transition_directory.glob("*.*"))

    shards: list[WindowShard] = []
    current_shard: WindowShard = WindowShard(shard_id=0, transition_files=[])

    for transition_file in tqdm(transition_files, desc="Sharding transition files..."):
        if transition_file.suffix.lower() not in [".csv", ".parquet"]:
            print(f"Skipping non-CSV/Parquet file: {transition_file}")
            continue

        num_transitions = get_transition_count(transition_file)
        estimated_expanded_size_gb = estimate_file_size_gb(num_transitions, temporal_window_size)

        current_shard_size_gb = current_shard.estimated_size_gb

        if current_shard_size_gb + estimated_expanded_size_gb > max_shard_size_gb and current_shard.transition_files:
            new_shard_idx = current_shard.shard_id + 1
            shards.append(current_shard)
            current_shard = WindowShard(shard_id=new_shard_idx, transition_files=[], estimated_sizes_gb=[])

        current_shard.transition_files.append(transition_file)
        current_shard.estimated_sizes_gb.append(estimated_expanded_size_gb)

    if current_shard.transition_files:
        shards.append(current_shard)

    return shards


        

def main():

    args = parse_args()

    temporal_window_size = args.window_context_size + args.window_target_size

    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir)

    if not input_dir.exists() or not input_dir.is_dir():
        raise ValueError(f"Input directory '{input_dir}' does not exist or is not a directory.")
    
    output_dir.mkdir(parents=True, exist_ok=True)

    # Create Shards from Trasition Data, in an expanded Temporal Window State.
    transition_shards = shard_transition_files(
        transition_directory=input_dir,
        temporal_window_size=temporal_window_size,
        max_shard_size_gb=args.max_shard_size
    )

    print(f"Created {len(transition_shards)} shards from transition files.")

if __name__ == "__main__":
    main()